name: Check
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      # - run: npm test
      - run: npx prettier . -c
      - run: npx eslint index.js
      - run: cd client
      - run: npm ci
      - run: npx eslint .
      # - run: npm test
